version: '3.8'

services:
  expenses_db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses_db
    volumes:
      - expenses_data:/var/lib/postgresql/data

  timeoffs_db:
    image: postgres:15
    ports:
      - "5435:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timeoffs_db
    volumes:
      - timeoffs_data:/var/lib/postgresql/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-thesis}"
    image: localstack/localstack
    network_mode: bridge
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      - "//var/run/docker.sock:/var/run/docker.sock"

volumes:
  expenses_data:
  timeoffs_data:
